
services:
  postgis:
    image: postgis/postgis:16-3.4 # Specifies PostgreSQL 16 with PostGIS 3.4
    platform: linux/amd64
    container_name: mariupol_postgis
    restart: unless-stopped
    ports:
      - "5432:5432" # Maps container port 5432 to your host machine's port 5432
    environment:
      POSTGRES_DB: mariupol_toponyms
      POSTGRES_USER: mariupol_researcher
      POSTGRES_PASSWORD: ChUzmZMy9g2mPsS*$yUtSY
      
    volumes:
      # Data persistence: This ensures your database data isn't lost when the container stops
      - postgis_data:/var/lib/postgresql/data
      # Initialization scripts: Docker will run SQL files in this directory when the container starts for the first time
      - ./sql/setup:/docker-entrypoint-initdb.d
      # Backup location: Maps a folder inside the container to a folder on your host for backups
      - ./data/backups:/backups
      
    # Resource limits for Mac Air (important for your system)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'

volumes:
  postgis_data:
    driver: local